openapi: 3.0.1
info:
  title: Order API - GET Operations (Basic Auth)
  version: "2.0"
servers:
  - url: "http://localhost:3000"
paths:
  "/products/{id}":
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        examples:
          GET_DETAILS:
            value: 10
          INVALID_ID:
            value: "344"
    get:
      summary: Fetch product details
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/Product"
              examples:
                GET_DETAILS:
                  value:
                    name: "XYZ Phone"
                    type: "gadget"
                    inventory: 10
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
              examples:
                INVALID_ID:
                  value:
                    timestamp: "2023-03-17T12:06:56.177+00:00"
                    status: 404
                    error: "Not Found"
                    message: "Not found"
      operationId: get-product-id
  /products:
    get:
      summary: GET Products based on type
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum:
              - gadget
              - book
              - food
              - other
      responses:
        "200":
          description: List of products in the response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "common.yaml#/components/schemas/Product"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
  /orders:
    get:
      summary: Search for orders
      operationId: get-orders
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./common.yaml#/components/schemas/Order"
              examples:
                200_OK:
                  value:
                    - productid: 10
                      count: 2
                      status: "pending"
                      id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      parameters:
        - schema:
            type: integer
          in: query
          name: productid
          examples:
            200_OK:
              value: 10
        - schema:
            type: string
          in: query
          name: status
          examples:
            200_OK:
              value: fulfilled
      description: ""
  "/orders/{id}":
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        examples:
          DETAILS:
            value: 10
          INVALID_ID:
            value: 433
    get:
      summary: Fetch order details
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/Order"
              examples:
                DETAILS:
                  value:
                    productid: 10
                    count: 2
                    status: "pending"
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
              examples:
                INVALID_ID:
                  value:
                    timestamp: "2023-03-17T12:06:56.177+00:00"
                    status: 404
                    error: "Not Found"
                    message: "Product with id 344 was not found"
      operationId: get-orders-id
      parameters: []
components:
  schemas:
    ErrorResponseBody:
      properties:
        id:
          type: number
        timestamp:
          type: string
        status:
          type: number
        error:
          type: string
        message:
          type: string

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic Authentication with username and password

security:
  - basicAuth: []

